/* ============================================================================
   CONTENIDO DEL PORTAFOLIO
   Este es el ÚNICO archivo que necesitas editar para personalizar la web.
   Todo lo que escribas aquí aparece automáticamente en la página.

   Para cambiar textos, edita este archivo. Los bloques "es" y "en" deben
   mantener la misma estructura.
   ========================================================================= */

const PROFILE = {
  name: "Ferley Orobio",
  initials: "FO",
  email: "Ferleyorobio68@gmail.com",
  phone: "+57 315 456 8446",
  location: "Cali, Colombia",
  social: {
    github: "https://github.com/FERLEY2004",
    linkedin: "https://www.linkedin.com/in/orobio-paz-ferley-ab50212ab/",
    twitter: "",
    website: "",
  },
  // Cuando tengas el CV en PDF, guárdalo en la carpeta assets y pon aquí la ruta
  // ("assets/CV.pdf"). Mientras estén vacías, el botón de descarga no aparece.
  cvEs: "assets/CV.pdf",
  cvEn: "assets/CV-EN.pdf",
  // Formulario de contacto: crea un formulario gratis en https://formspree.io
  // y pega aquí la URL (ej. "https://formspree.io/f/abcdwxyz").
  // Si lo dejas vacío, el formulario abrirá el gestor de correo del visitante.
  formEndpoint: "",
  available: true,
};

const CONTENT = {
  /* ==========================================================================
     ESPAÑOL
     ====================================================================== */
  es: {
    langLabel: "ES",
    nav: {
      services: "Servicios",
      work: "Proyectos",
      about: "Sobre mí",
      experience: "Experiencia",
      contact: "Contacto",
      cta: "Hablemos",
    },
    hero: {
      badge: "Disponible para trabajar",
      badgeOff: "Sin disponibilidad por ahora",
      greeting: "Hola, soy",
      role: "Desarrollador Full Stack",
      tagline:
        "Construyo software que automatiza el trabajo de las empresas: chatbots con inteligencia artificial en WhatsApp, sistemas de inventario y logística, integraciones con ERP y comercio electrónico. Del diseño de la base de datos hasta la pantalla que usa el cliente.",
      ctaPrimary: "Ver proyectos",
      ctaSecondary: "Descargar CV",
      scroll: "Desliza",
      stats: [
        { value: "5", label: "años programando" },
        { value: "2", label: "años de experiencia certificada" },
        { value: "7", label: "sistemas desarrollados" },
      ],
    },
    services: {
      eyebrow: "Servicios",
      title: "En qué puedo ayudarte",
      subtitle:
        "Trabajo en remoto para clientes de cualquier ciudad. Cada entrega incluye el código fuente, la base de datos documentada y acompañamiento para ponerlo en marcha.",
      items: [
        {
          icon: "bot",
          title: "Chatbots con IA para WhatsApp",
          text: "Automatizo la atención al cliente con un asistente que responde por WhatsApp las 24 horas: consulta tu catálogo, informa precios y disponibilidad, arma cotizaciones y pasa la conversación a un asesor cuando hace falta.",
          bullets: ["Integración con OpenAI y Meta WhatsApp API", "Conectado a tu inventario real", "Transferencia a un asesor humano"],
          price: "Presupuesto a medida",
        },
        {
          icon: "boxes",
          title: "Sistemas de inventario y logística",
          text: "Control de stock en varias bodegas y puntos de venta, alertas de inventario bajo, pedidos, traslados entre sedes y seguimiento de vehículos, rutas y conductores. Con exportación a Excel.",
          bullets: ["Multi-bodega y multi-sede", "Alertas de stock bajo", "Trazabilidad y reportes"],
          price: "Presupuesto a medida",
        },
        {
          icon: "plug",
          title: "Integraciones y APIs",
          text: "Conecto los sistemas que ya usas para que dejen de hablarse por correo y planilla. Sincronización de información con tu ERP, automatización de procesos y APIs REST a la medida de tu operación.",
          bullets: ["APIs REST y webhooks", "Sincronización con ERP", "Automatización de procesos"],
          price: "Presupuesto a medida",
        },
        {
          icon: "cart",
          title: "Comercio electrónico y aplicaciones web",
          text: "Tiendas en línea con catálogo, carrito y pasarela de pago, o aplicaciones a medida con inicio de sesión, roles de usuario, panel de administración y reportes.",
          bullets: ["Catálogo, carrito y pagos", "Roles y permisos", "Panel de administración"],
          price: "Presupuesto a medida",
        },
      ],
    },
    process: {
      eyebrow: "Método",
      title: "Cómo trabajo",
      subtitle: "Un proceso claro, con fechas y entregas definidas desde el primer día.",
      steps: [
        { title: "Conversamos", text: "Una llamada sin costo para entender qué proceso quieres resolver, quién lo usará y con qué presupuesto cuentas." },
        { title: "Propuesta por escrito", text: "Alcance, tiempos y precio cerrado antes de empezar. Sabes exactamente qué recibes y cuándo." },
        { title: "Entregas por partes", text: "Te muestro avances cada semana para que puedas opinar y corregir mientras todavía es sencillo hacerlo." },
        { title: "Puesta en marcha", text: "Publico el sistema, capacito a tu equipo para que lo administre y te acompaño durante el primer mes." },
      ],
    },
    skills: {
      eyebrow: "Stack",
      title: "Tecnologías con las que trabajo",
      groups: [
        { title: "Desarrollo", items: ["JavaScript", "TypeScript", "C#", ".NET / ASP.NET Core", "Node.js", "React", "React Native", "Capacitor", "Electron", "HTML5", "CSS3", "Tailwind CSS"] },
        { title: "Backend y APIs", items: ["Express.js", "API REST", "Webhooks", "JWT", "Autenticación y autorización", "Control de acceso por roles"] },
        { title: "Bases de datos", items: ["SQL Server", "MySQL", "PostgreSQL", "Prisma", "Diseño de bases de datos", "Modelado de datos", "Optimización de consultas"] },
        { title: "Inteligencia artificial", items: ["OpenAI API", "IA conversacional", "Function Calling", "Agentes de IA", "Prompt Engineering", "IA aplicada a procesos"] },
        { title: "Integraciones", items: ["Meta WhatsApp API", "Twilio", "Webhooks", "Integración con ERP", "Pasarelas de pago", "APIs de terceros"] },
        { title: "Herramientas", items: ["Git", "GitHub", "Docker", "Postman", "Vite", "VS Code", "Visual Studio"] },
        { title: "También uso", items: ["SQL", "GitHub Actions", "AWS", "npm", "Excel", "Claude Code", "Codex", "Antigravity"] },
      ],
    },
    work: {
      eyebrow: "Portafolio",
      title: "Proyectos",
      subtitle:
        "Sistemas que he construido de principio a fin: base de datos, servidor e interfaz. Algunos son de clientes y su código es privado; los que puedo mostrar tienen enlace al repositorio. iParceStore está en desarrollo activo.",
      filterAll: "Todos",
      demo: "Ver demo",
      code: "Ver código",
      items: [
        {
          title: "iParceStore — marketplace para Colombia",
          category: "Marketplace",
          text: "Plataforma tipo Temu, enfocada inicialmente en Colombia, donde distintos vendedores publican y venden sus propios productos. Incluye publicaciones, búsqueda, perfil de vendedor, chat interno, calificaciones, variantes (talla y color), ubicación por departamento, municipio y vereda, cálculo de envíos y pagos con pasarela autorizada (Wompi, PayU, ePayco o Mercado Pago). El mismo frontend se empaqueta como app móvil con Capacitor. Verificación de identidad y protección de transacciones forman parte del diseño.",
          result: "En desarrollo — modelo multivendedor",
          tags: ["React", "TypeScript", "Vite", "Tailwind CSS", "Node.js", "Express", "PostgreSQL", "Prisma", "JWT", "Capacitor"],
          demo: "",
          code: "",
          featured: true,
        },
        {
          title: "Chatbots empresariales con inteligencia artificial",
          category: "Inteligencia artificial",
          text: "Asistentes de WhatsApp que atienden a los clientes de forma automática: consultan catálogo, precios e inventario, generan cotizaciones y transfieren la conversación a un asesor cuando el caso lo requiere. Usan Function Calling para conectar la inteligencia artificial con los procesos reales de la empresa, y manejan contexto de conversación y campañas de mensajería.",
          result: "Atención al cliente automatizada 24/7",
          tags: ["Node.js", "Express", "OpenAI API", "Meta WhatsApp API", "Twilio", "Webhooks", "SQL"],
          demo: "",
          code: "",
          featured: true,
        },
        {
          title: "Sistema de inventario y logística",
          category: "Sistemas empresariales",
          text: "Gestión de inventario en varias bodegas y puntos de venta, con control de stock, alertas de existencias bajas, pedidos, requisiciones y transferencias entre sedes. Incluye trazabilidad de cada operación con evidencias, administración de vehículos, rutas, conductores y horarios, y exportación de la información a Excel.",
          result: "Multi-bodega y multi-punto de venta",
          tags: ["Node.js", "Express", "SQL Server", "API REST"],
          demo: "",
          code: "",
          featured: false,
        },
        {
          title: "Sistema de control de acceso SENA",
          category: "Control de acceso",
          text: "Control del ingreso de personal mediante códigos QR y biometría, con validación automática del estado de cada usuario. Incluye registro e historial completo de accesos, panel administrativo y generación de reportes.",
          result: "Validación por QR y biometría",
          tags: ["React Native", "Electron", "Node.js", "SQL", "API REST"],
          demo: "",
          code: "https://github.com/FERLEY2004/sistema-control-acceso-qr",
          featured: false,
        },
        {
          title: "BikeStore — tienda de bicicletas en línea",
          category: "E-commerce",
          text: "Plataforma de comercio electrónico para la venta de bicicletas, con catálogo de productos, carrito de compras y autenticación de clientes. Incluye panel administrativo, gestión de usuarios y control de roles y permisos.",
          result: "Carrito, pagos y panel de administración",
          tags: ["Node.js", "MySQL", "JavaScript", "HTML", "CSS"],
          demo: "",
          code: "https://github.com/FERLEY2004/bikestore_entrega",
          featured: false,
        },
        {
          title: "Sistemas administrativos empresariales",
          category: "Sistemas empresariales",
          text: "Módulos para la gestión y el seguimiento de procesos internos en áreas de logística, informática y gestión humana. Con administración de usuarios, roles y permisos, además de reportes y herramientas de monitoreo.",
          result: "Módulos para logística, TI y gestión humana",
          tags: ["Node.js", "Express", "SQL Server", "API REST"],
          demo: "",
          code: "",
          featured: false,
        },
        {
          title: "Integraciones empresariales y ERP",
          category: "Sistemas empresariales",
          text: "Desarrollo de APIs para conectar aplicaciones internas con el ecosistema de la empresa, sincronizando información entre sistemas que antes no se comunicaban y automatizando procesos operativos y administrativos.",
          result: "Sincronización entre sistemas",
          tags: ["Node.js", "Express", "SQL Server", "API REST"],
          demo: "",
          code: "",
          featured: false,
        },
      ],
    },
    about: {
      eyebrow: "Sobre mí",
      title: "Desarrollador full stack enfocado en automatizar procesos",
      paragraphs: [
        "Llevo cinco años programando. Me formé como tecnólogo profesional en Análisis y Desarrollo de Software en el SENA y completé un año de certificación en Burica S.A. El resto del camino lo construí con proyectos propios. Hoy estoy construyendo iParceStore, un marketplace para Colombia.",
        "Trabajo de punta a punta. Diseño la base de datos, levanto el backend con Node.js o .NET, construyo la API y armo la interfaz que ve el usuario. Eso me permite entender cómo encaja cada pieza y anticipar dónde se va a romper algo antes de que llegue a producción.",
        "En el último tiempo me he concentrado en aplicar inteligencia artificial a procesos reales de negocio: chatbots de WhatsApp conectados al inventario y al catálogo de la empresa, capaces de cotizar y de escalar la conversación a una persona cuando hace falta. No es IA por moda, es IA resolviendo algo que antes ocupaba a alguien todo el día.",
        "Busco vincularme a un equipo donde pueda seguir creciendo en arquitectura de software y trabajar cerca del problema del negocio, no solo del código.",
      ],
      highlights: [
        "Full stack real: base de datos, backend, API e interfaz",
        "Experiencia en sistemas empresariales en producción",
        "Integración de IA con procesos de negocio",
        "Disponible para trabajo remoto o presencial en Cali",
      ],
      photoAlt: "Retrato de Ferley Orobio",
    },
    experience: {
      eyebrow: "Trayectoria",
      title: "Experiencia y formación",
      tabWork: "Experiencia",
      tabEdu: "Formación",
      jobs: [
        {
          date: "Actualidad",
          role: "Desarrollador Full Stack",
          org: "Proyectos propios",
          text: "Diseño y desarrollo de sistemas a medida y, en la actualidad, de iParceStore, un marketplace multivendedor para Colombia. También chatbots con inteligencia artificial para WhatsApp, inventario y logística, integraciones con ERP, comercio electrónico y control de acceso.",
        },
        {
          date: "1 año",
          role: "Desarrollador de software",
          org: "Burica S.A.",
          text: "Estancia de un año en la empresa para completar la certificación profesional. Trabajo en un entorno empresarial real, aplicando el ciclo de desarrollo de software a procesos de la organización.",
        },
      ],
      education: [
        {
          date: "SENA",
          role: "Tecnólogo profesional en Análisis y Desarrollo de Software",
          org: "Servicio Nacional de Aprendizaje (SENA)",
          text: "Formación en análisis, diseño y construcción de software, bases de datos, APIs y desarrollo full stack, con énfasis en resolver problemas reales de negocio.",
        },
        {
          date: "SENA",
          role: "Profesional en desarrollo de software",
          org: "Servicio Nacional de Aprendizaje (SENA)",
          text: "Formación profesional centrada en el ciclo completo de desarrollo: requisitos, implementación, pruebas y puesta en marcha de aplicaciones.",
        },
        {
          date: "SENA",
          role: "Cursos complementarios",
          org: "Servicio Nacional de Aprendizaje (SENA)",
          text: "Ciberseguridad, tecnologías de la información y la comunicación (TICs), Internet de las cosas (IoT) y DevOps.",
        },
        {
          date: "MinTIC",
          role: "Curso intensivo de programación",
          org: "Ministerio de Educación Nacional y MinTIC",
          text: "Formación intensiva en programación impulsada por el Ministerio de Educación Nacional y el Ministerio de Tecnologías de la Información y las Comunicaciones.",
        },
        {
          date: "Platzi",
          role: "Cursos de formación continua",
          org: "Platzi",
          text: ".NET, C#, CSS3, HTML5 y AWS.",
        },
      ],
    },
    contact: {
      eyebrow: "Contacto",
      title: "Cuéntame qué necesitas",
      subtitle:
        "Respondo en menos de 24 horas. Si prefieres, escríbeme directamente al correo o por LinkedIn.",
      formName: "Nombre",
      formEmail: "Correo electrónico",
      formSubject: "Asunto",
      formMessage: "Mensaje",
      formPlaceholderName: "Cómo te llamas",
      formPlaceholderEmail: "tu@correo.com",
      formMessagePlaceholder: "Cuéntame brevemente qué necesitas, para cuándo lo necesitas y con qué presupuesto cuentas.",
      subjects: ["Oferta de empleo", "Proyecto freelance", "Colaboración", "Otro"],
      send: "Enviar mensaje",
      sending: "Enviando...",
      success: "Mensaje enviado. Te respondo pronto.",
      error: "No se pudo enviar. Escríbeme directamente a",
      copy: "Copiar",
      copied: "Copiado",
      infoTitle: "Datos de contacto",
      availability: "Disponibilidad",
      availabilityText: "Abierto a ofertas de empleo y proyectos freelance",
      availabilityOff: "Sin disponibilidad para nuevos proyectos",
      response: "Tiempo de respuesta",
      responseText: "Menos de 24 horas",
    },
    errors: {
      name: "Escribe tu nombre",
      email: "Escribe un correo válido",
      message: "Cuéntame un poco más (mínimo 20 caracteres)",
    },
    footer: {
      tagline: "Software empresarial y automatización desde Cali, Colombia.",
      rights: "Todos los derechos reservados.",
      built: "Diseñado y programado por mí, sin plantillas.",
      backToTop: "Volver arriba",
    },
    theme: { toLight: "Cambiar a tema claro", toDark: "Cambiar a tema oscuro" },
    menu: { open: "Abrir menú", close: "Cerrar menú" },
  },

  /* ==========================================================================
     ENGLISH
     ====================================================================== */
  en: {
    langLabel: "EN",
    nav: {
      services: "Services",
      work: "Work",
      about: "About",
      experience: "Experience",
      contact: "Contact",
      cta: "Let's talk",
    },
    hero: {
      badge: "Available for hire",
      badgeOff: "Not available right now",
      greeting: "Hi, I'm",
      role: "Full Stack Developer",
      tagline:
        "I build software that automates how companies work: AI-powered WhatsApp chatbots, inventory and logistics systems, ERP integrations and e-commerce. From database design to the screen the customer uses.",
      ctaPrimary: "View work",
      ctaSecondary: "Download CV",
      scroll: "Scroll",
      stats: [
        { value: "5", label: "years coding" },
        { value: "2", label: "years of certified experience" },
        { value: "7", label: "systems built" },
      ],
    },
    services: {
      eyebrow: "Services",
      title: "How I can help",
      subtitle:
        "I work remotely with clients anywhere. Every delivery includes the source code, a documented database and support to get it running.",
      items: [
        {
          icon: "bot",
          title: "AI chatbots for WhatsApp",
          text: "I automate customer service with an assistant that answers on WhatsApp around the clock: it checks your catalogue, reports prices and availability, builds quotes and hands the conversation to a human when needed.",
          bullets: ["OpenAI and Meta WhatsApp API integration", "Connected to your real inventory", "Handover to a human agent"],
          price: "Custom quote",
        },
        {
          icon: "boxes",
          title: "Inventory and logistics systems",
          text: "Stock control across multiple warehouses and points of sale, low-stock alerts, orders, transfers between locations, and tracking of vehicles, routes and drivers. With Excel export.",
          bullets: ["Multi-warehouse and multi-site", "Low-stock alerts", "Traceability and reports"],
          price: "Custom quote",
        },
        {
          icon: "plug",
          title: "Integrations and APIs",
          text: "I connect the systems you already use so they stop communicating through email and spreadsheets. Data synchronisation with your ERP, process automation and REST APIs tailored to your operation.",
          bullets: ["REST APIs and webhooks", "ERP synchronisation", "Process automation"],
          price: "Custom quote",
        },
        {
          icon: "cart",
          title: "E-commerce and web applications",
          text: "Online stores with catalogue, cart and payment gateway, or custom applications with login, user roles, admin panel and reporting.",
          bullets: ["Catalogue, cart and payments", "Roles and permissions", "Admin dashboard"],
          price: "Custom quote",
        },
      ],
    },
    process: {
      eyebrow: "Method",
      title: "How I work",
      subtitle: "A clear process, with dates and deliverables agreed from day one.",
      steps: [
        { title: "We talk", text: "A free call to understand which process you want to solve, who will use it and what budget you have." },
        { title: "Written proposal", text: "Scope, timeline and fixed price before we start. You know exactly what you get and when." },
        { title: "Phased delivery", text: "I show you progress every week so you can weigh in and change course while it's still easy." },
        { title: "Launch", text: "I deploy the system, train your team to run it and stay available through the first month." },
      ],
    },
    skills: {
      eyebrow: "Stack",
      title: "Technologies I work with",
      groups: [
        { title: "Development", items: ["JavaScript", "TypeScript", "C#", ".NET / ASP.NET Core", "Node.js", "React", "React Native", "Capacitor", "Electron", "HTML5", "CSS3", "Tailwind CSS"] },
        { title: "Backend and APIs", items: ["Express.js", "REST API", "Webhooks", "JWT", "Authentication and authorisation", "Role-based access control"] },
        { title: "Databases", items: ["SQL Server", "MySQL", "PostgreSQL", "Prisma", "Database design", "Data modelling", "Query optimisation"] },
        { title: "Artificial intelligence", items: ["OpenAI API", "Conversational AI", "Function Calling", "AI agents", "Prompt engineering", "AI applied to business processes"] },
        { title: "Integrations", items: ["Meta WhatsApp API", "Twilio", "Webhooks", "ERP integration", "Payment gateways", "Third-party APIs"] },
        { title: "Tools", items: ["Git", "GitHub", "Docker", "Postman", "Vite", "VS Code", "Visual Studio"] },
        { title: "Also using", items: ["SQL", "GitHub Actions", "AWS", "npm", "Excel", "Claude Code", "Codex", "Antigravity"] },
      ],
    },
    work: {
      eyebrow: "Portfolio",
      title: "Projects",
      subtitle:
        "Systems I've built end to end: database, server and interface. Some belong to clients and their code is private; the ones I can show link to the repository. iParceStore is in active development.",
      filterAll: "All",
      demo: "Live demo",
      code: "Source code",
      items: [
        {
          title: "iParceStore — marketplace for Colombia",
          category: "Marketplace",
          text: "A Temu-style platform, starting in Colombia, where different sellers list and sell their own products. It includes listings, search, seller profiles, in-app chat, ratings, variants (size and colour), location by department, municipality and village, shipping cost calculation and payments through an authorised gateway (Wompi, PayU, ePayco or Mercado Pago). The same frontend is packaged as a mobile app with Capacitor. Identity verification and transaction protection are part of the design.",
          result: "In development — multi-vendor model",
          tags: ["React", "TypeScript", "Vite", "Tailwind CSS", "Node.js", "Express", "PostgreSQL", "Prisma", "JWT", "Capacitor"],
          demo: "",
          code: "",
          featured: true,
        },
        {
          title: "Enterprise AI chatbots",
          category: "Artificial intelligence",
          text: "WhatsApp assistants that serve customers automatically: they check the catalogue, prices and inventory, generate quotes and hand the conversation to a human agent when the case calls for it. They use Function Calling to connect the AI to the company's real processes, and manage conversation context and messaging campaigns.",
          result: "Automated customer service, 24/7",
          tags: ["Node.js", "Express", "OpenAI API", "Meta WhatsApp API", "Twilio", "Webhooks", "SQL"],
          demo: "",
          code: "",
          featured: true,
        },
        {
          title: "Inventory and logistics system",
          category: "Enterprise systems",
          text: "Inventory management across multiple warehouses and points of sale, with stock control, low-stock alerts, orders, requisitions and transfers between locations. Includes traceability of every operation with supporting evidence, management of vehicles, routes, drivers and schedules, and Excel export.",
          result: "Multi-warehouse and multi-store",
          tags: ["Node.js", "Express", "SQL Server", "REST API"],
          demo: "",
          code: "",
          featured: false,
        },
        {
          title: "SENA access control system",
          category: "Access control",
          text: "Staff entry control through QR codes and biometrics, with automatic validation of each user's status. Includes a full access log and history, admin panel and report generation.",
          result: "QR and biometric validation",
          tags: ["React Native", "Electron", "Node.js", "SQL", "REST API"],
          demo: "",
          code: "https://github.com/FERLEY2004/sistema-control-acceso-qr",
          featured: false,
        },
        {
          title: "BikeStore — online bicycle shop",
          category: "E-commerce",
          text: "E-commerce platform for selling bicycles, with product catalogue, shopping cart and customer authentication. Includes an admin panel, user management and role and permission control.",
          result: "Cart, payments and admin dashboard",
          tags: ["Node.js", "MySQL", "JavaScript", "HTML", "CSS"],
          demo: "",
          code: "https://github.com/FERLEY2004/bikestore_entrega",
          featured: false,
        },
        {
          title: "Enterprise administrative systems",
          category: "Enterprise systems",
          text: "Modules to manage and track internal processes across logistics, IT and human resources. With user, role and permission administration, plus reporting and monitoring tools.",
          result: "Modules for logistics, IT and HR",
          tags: ["Node.js", "Express", "SQL Server", "REST API"],
          demo: "",
          code: "",
          featured: false,
        },
        {
          title: "Enterprise and ERP integrations",
          category: "Enterprise systems",
          text: "API development to connect internal applications with the company's ecosystem, synchronising data between systems that previously didn't talk to each other and automating operational and administrative processes.",
          result: "Synchronisation across systems",
          tags: ["Node.js", "Express", "SQL Server", "REST API"],
          demo: "",
          code: "",
          featured: false,
        },
      ],
    },
    about: {
      eyebrow: "About me",
      title: "A full stack developer focused on automating processes",
      paragraphs: [
        "I've been coding for five years. I trained as a professional technologist in Software Analysis and Development at SENA and completed a one-year certification placement at Burica S.A. The rest of the way I built through my own projects. Right now I'm building iParceStore, a marketplace for Colombia.",
        "I work end to end. I design the database, build the backend with Node.js or .NET, expose the API and put together the interface the user sees. That lets me understand how each piece fits and anticipate where something will break before it reaches production.",
        "Lately I've focused on applying artificial intelligence to real business processes: WhatsApp chatbots wired into a company's inventory and catalogue, able to quote and to escalate to a person when needed. It isn't AI for the sake of it, it's AI solving something that used to take someone all day.",
        "I'm looking to join a team where I can keep growing in software architecture and work close to the business problem, not just the code.",
      ],
      highlights: [
        "Genuinely full stack: database, backend, API and interface",
        "Experience with enterprise systems in production",
        "AI integrated into business processes",
        "Available for remote work or on-site in Cali",
      ],
      photoAlt: "Portrait of Ferley Orobio",
    },
    experience: {
      eyebrow: "Background",
      title: "Experience and education",
      tabWork: "Experience",
      tabEdu: "Education",
      jobs: [
        {
          date: "Present",
          role: "Full Stack Developer",
          org: "Independent projects",
          text: "Design and development of custom systems and, currently, of iParceStore, a multi-vendor marketplace for Colombia. Also AI-powered WhatsApp chatbots, inventory and logistics, ERP integrations, e-commerce and access control.",
        },
        {
          date: "1 year",
          role: "Software Developer",
          org: "Burica S.A.",
          text: "One-year placement at the company to complete professional certification. Work in a real business environment, applying the software development cycle to organisational processes.",
        },
      ],
      education: [
        {
          date: "SENA",
          role: "Professional Technologist in Software Analysis and Development",
          org: "National Learning Service (SENA)",
          text: "Training in software analysis, design and construction, databases, APIs and full stack development, with a focus on solving real business problems.",
        },
        {
          date: "SENA",
          role: "Professional in Software Development",
          org: "National Learning Service (SENA)",
          text: "Professional training covering the full development cycle: requirements, implementation, testing and bringing applications into production.",
        },
        {
          date: "SENA",
          role: "Complementary courses",
          org: "National Learning Service (SENA)",
          text: "Cybersecurity, information and communication technologies (ICTs), Internet of Things (IoT) and DevOps.",
        },
        {
          date: "MinTIC",
          role: "Intensive programming course",
          org: "Ministry of National Education and MinTIC",
          text: "Intensive programming training delivered by Colombia's Ministry of National Education and the Ministry of Information and Communication Technologies.",
        },
        {
          date: "Platzi",
          role: "Continuing education courses",
          org: "Platzi",
          text: ".NET, C#, CSS3, HTML5 and AWS.",
        },
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Tell me what you need",
      subtitle:
        "I reply within 24 hours. If you prefer, reach out directly by email or on LinkedIn.",
      formName: "Name",
      formEmail: "Email",
      formSubject: "Subject",
      formMessage: "Message",
      formPlaceholderName: "Your name",
      formPlaceholderEmail: "you@email.com",
      formMessagePlaceholder: "Briefly describe what you need, when you need it and the budget you have in mind.",
      subjects: ["Job opportunity", "Freelance project", "Collaboration", "Other"],
      send: "Send message",
      sending: "Sending...",
      success: "Message sent. I'll get back to you soon.",
      error: "Couldn't send it. Please email me directly at",
      copy: "Copy",
      copied: "Copied",
      infoTitle: "Contact details",
      availability: "Availability",
      availabilityText: "Open to job offers and freelance projects",
      availabilityOff: "Not taking on new projects",
      response: "Response time",
      responseText: "Under 24 hours",
    },
    errors: {
      name: "Please enter your name",
      email: "Please enter a valid email",
      message: "Tell me a bit more (at least 20 characters)",
    },
    footer: {
      tagline: "Enterprise software and automation from Cali, Colombia.",
      rights: "All rights reserved.",
      built: "Designed and coded by me, no templates.",
      backToTop: "Back to top",
    },
    theme: { toLight: "Switch to light theme", toDark: "Switch to dark theme" },
    menu: { open: "Open menu", close: "Close menu" },
  },
};
